#!/usr/bin/env bash
# ===========================================================================
# Melos Runner & Direct Execution Fallback
# Handles script detection, argument resolution, and fallback direct flutter execution.
# ===========================================================================
set -euo pipefail

#------------------------------------------------------------------------------
# melosScriptEnv - Map env names to melos script naming.
#------------------------------------------------------------------------------
melosScriptEnv() {
    local env_name="${1:-}"
    local app_name="${2:-}"
    echo "$env_name"
}

#------------------------------------------------------------------------------
# checkMelosScript - Check if a melos script exists in the pubspec.yaml file.
#------------------------------------------------------------------------------
checkMelosScript() {
    local script_name="${1:-}"
    if [ -z "$script_name" ]; then
        return 0
    fi
    
    local root="${MELOS_ROOT_PATH:-}"
    if [ -z "$root" ]; then
        root="$(pwd | sed -E 's|/apps/[^/]+||' | sed -E 's|/packages/[^/]+||')"
    fi
    
    local pubspec_file="$root/pubspec.yaml"
    if [ ! -f "$pubspec_file" ]; then
        return 0
    fi
    
    if ! grep -q "^[[:space:]]*${script_name}:[[:space:]]*$" "$pubspec_file"; then
        echo "================================================================================"
        echo "❌ ERROR: Melos script '${script_name}' could not be found in pubspec.yaml."
        echo "Please verify the script name or regenerate your workspace scripts using:"
        echo "  dart developer-dashboard/features/deployment/melos/merge_scripts.dart"
        echo "================================================================================"
        return 1
    fi
    return 0
}

#------------------------------------------------------------------------------
# getMelosScriptName - Resolves the actual Melos script name, handling apps 
# with and without flavor suffixes (e.g., app:deploy:prod:ipa:raw vs app:deploy:ipa:raw).
#------------------------------------------------------------------------------
getMelosScriptName() {
    local app_name="$1"
    local action="$2" # build / deploy / upload
    local env_name="$3" # prod / dev / test
    local format="$4" # ipa:raw / aab:raw / aab / etc.
    
    local root="${MELOS_ROOT_PATH:-}"
    if [ -z "$root" ]; then
        root="$(pwd | sed -E 's|/apps/[^/]+||' | sed -E 's|/packages/[^/]+||')"
    fi
    
    local pubspec_file="$root/pubspec.yaml"
    
    # 1. Try script name WITH the environment name (e.g., app:deploy:prod:ipa:raw)
    local script_with_env="$app_name:$action:$env_name:$format"
    if [ -f "$pubspec_file" ] && grep -q "^[[:space:]]*${script_with_env}:[[:space:]]*$" "$pubspec_file"; then
        echo "$script_with_env"
        return 0
    fi
    
    # 2. Try script name WITHOUT the environment name (e.g., app:deploy:ipa:raw)
    local script_without_env="$app_name:$action:$format"
    if [ -f "$pubspec_file" ] && grep -q "^[[:space:]]*${script_without_env}:[[:space:]]*$" "$pubspec_file"; then
        echo "$script_without_env"
        return 0
    fi
    
    # Fallback to the one with env name if neither/both not found, to let checkMelosScript handle the error output
    echo "$script_with_env"
}

#------------------------------------------------------------------------------
# melosScriptExists - True when <script_name> is defined in the root pubspec.yaml.
# Unlike checkMelosScript, a missing pubspec.yaml counts as "not defined".
#------------------------------------------------------------------------------
melosScriptExists() {
    local script_name="${1:-}"
    local root="${MELOS_ROOT_PATH:-}"
    if [ -z "$root" ]; then
        root="$(pwd | sed -E 's|/apps/[^/]+||' | sed -E 's|/packages/[^/]+||')"
    fi
    [ -n "$script_name" ] && [ -f "$root/pubspec.yaml" ] \
        && grep -q "^[[:space:]]*${script_name}:[[:space:]]*$" "$root/pubspec.yaml"
}

#------------------------------------------------------------------------------
# directRawAction - run_build.sh function that a "<app>:<action>[:<env>]:<format>"
# Melos script would have wrapped. Those scripts (TYRIOS-style, generated by
# merge_scripts.dart) are thin wrappers around these functions, which build
# with flutter directly inside resolveAppDir.
#------------------------------------------------------------------------------
directRawAction() {
    case "$1:$2" in
        build:aab:raw)  echo "buildAABRaw" ;;
        deploy:aab:raw) echo "buildAndUploadAndroid" ;;
        build:ipa:raw)  echo "buildIPARaw" ;;
        deploy:ipa:raw) echo "buildAndUploadIOS" ;;
        upload:ipa:raw) echo "uploadIPARaw" ;;
        *) return 1 ;;
    esac
}

#------------------------------------------------------------------------------
# runMelosOrDirect - Run the workspace's Melos script for <app>/<action>/<env>/<format>
# when it exists; otherwise run the equivalent direct function (flutter in the
# app folder) so any Melos workspace works without injected scripts.
# USAGE: runMelosOrDirect [--notify] <app_name> <action> <env_name> <format>
#------------------------------------------------------------------------------
runMelosOrDirect() {
    local notify=false
    if [ "${1:-}" = "--notify" ]; then notify=true; shift; fi
    local app_name="$1" action="$2" env_name="$3" format="$4"
    local script_env target_script direct_fn
    script_env="$(melosScriptEnv "$env_name" "$app_name")"
    target_script="$(getMelosScriptName "$app_name" "$action" "$script_env" "$format")"

    local -a cmd
    if melosScriptExists "$target_script"; then
        cmd=(melos run "$target_script")
    elif direct_fn="$(directRawAction "$action" "$format")"; then
        echo "ℹ️  Melos script '$target_script' not defined; running $direct_fn directly in $(resolveAppDir "$app_name")"
        cmd=(bash "$JSON_SCRIPT_DIR/run_build.sh" "$direct_fn" "$app_name" "$env_name")
    else
        checkMelosScript "$target_script" || return 1
        cmd=(melos run "$target_script")
    fi

    if [ "$notify" = true ]; then
        bash "$CHAT_NOTIFY_PATH" -- "${cmd[@]}"
    else
        "${cmd[@]}"
    fi
}
