/**
 * setup_state.js — shared Setup modal state and DOM refs.
 * Loaded before the other modules/setup/*.js files, which use these at load time.
 */

const setupState = window.setupState = window.setupState || {
    apps: [],
    selectedAppId: null,
    deployConfig: { apps: {} },
    currentWebhooks: [],
};

const setupEls = window.setupEls = window.setupEls || {
    overlay: document.getElementById('setupOverlay'),
    openBtn: document.getElementById('openSetupBtn'),
    closeBtn: document.getElementById('closeSetupBtn'),
    appNav: document.getElementById('setupAppNav'),
    noApp: document.getElementById('setupNoApp'),
    form: document.getElementById('setupForm'),
    appTitle: document.getElementById('setupAppTitle'),
    appleId: document.getElementById('cfgAppleId'),
    issuerId: document.getElementById('cfgIssuerId'),
    playService: document.getElementById('cfgPlayService'),
    flavors: document.getElementById('cfgFlavors'),
    autoReleaseEnabled: document.getElementById('cfgAutoReleaseEnabled'),
    autoReleaseAction: document.getElementById('cfgAutoReleaseAction'),
    autoReleaseFlavors: document.getElementById('cfgAutoReleaseFlavors'),
    iosCertStatus: document.getElementById('iosCertStatus'),
    iosCertRecheckBtn: document.getElementById('iosCertRecheckBtn'),
    saveBtn: document.getElementById('saveConfigBtn'),
    regenerateBtn: document.getElementById('regenerateBtn'),
    scanBtn: document.getElementById('autoScanBtn'),
    scanAllBtn: document.getElementById('scanAllBtn'),
    // p8 upload elements
    p8Dropzone: document.getElementById('p8Dropzone'),
    p8FileInput: document.getElementById('p8FileInput'),
    p8DropzoneTitle: document.getElementById('p8DropzoneTitle'),
    p8UploadStatus: document.getElementById('p8UploadStatus'),
    p8CurrentKeyInfo: document.getElementById('p8CurrentKeyInfo'),
    p8CurrentKeyId: document.getElementById('p8CurrentKeyId'),
    p8CurrentKeyPath: document.getElementById('p8CurrentKeyPath'),
    // Notification webhook elements
    webhookUrl: document.getElementById('cfgWebhookUrl'),
    webhookEnabled: document.getElementById('cfgWebhookEnabled'),
    webhookProvider: document.getElementById('cfgWebhookProvider'),
    notifyOnSuccess: document.getElementById('cfgNotifyOnSuccess'),
    notifyOnFailure: document.getElementById('cfgNotifyOnFailure'),
    playConsoleTrack: document.getElementById('cfgPlayConsoleTrack'),
    wsWebhookUrl: document.getElementById('cfgWorkspaceWebhookUrl'),
    wsWebhookEnabled: document.getElementById('cfgWorkspaceWebhookEnabled'),
    wsWebhookProvider: document.getElementById('cfgWorkspaceWebhookProvider'),
    wsNotifyOnSuccess: document.getElementById('cfgWorkspaceNotifySuccess'),
    wsNotifyOnFailure: document.getElementById('cfgWorkspaceNotifyFailure'),
    testWebhookBtn: document.getElementById('testWebhookBtn'),
    testWebhookResult: document.getElementById('testWebhookResult'),
    openAddWebhookChannelBtn: document.getElementById('openAddWebhookChannelBtn'),
    webhookChannelsList: document.getElementById('webhookChannelsList'),
    webhookChannelsCountBadge: document.getElementById('webhookChannelsCountBadge'),
    webhookChannelModal: document.getElementById('webhookChannelModal'),
    closeWebhookChannelModalBtn: document.getElementById('closeWebhookChannelModalBtn'),
    cancelWebhookChannelBtn: document.getElementById('cancelWebhookChannelBtn'),
    saveWebhookChannelBtn: document.getElementById('saveWebhookChannelBtn'),
    channelModalId: document.getElementById('channelModalId'),
    channelModalTitle: document.getElementById('channelModalTitle'),
    channelModalName: document.getElementById('channelModalName'),
    channelModalUrl: document.getElementById('channelModalUrl'),
    channelModalProvider: document.getElementById('channelModalProvider'),
    channelModalPhone: document.getElementById('channelModalPhone'),
    channelModalTemplate: document.getElementById('channelModalTemplate'),
    channelModalHeaders: document.getElementById('channelModalHeaders'),
    channelModalSuccess: document.getElementById('channelModalSuccess'),
    channelModalFailure: document.getElementById('channelModalFailure'),
    channelModalEnabled: document.getElementById('channelModalEnabled'),
    channelModalTestBtn: document.getElementById('channelModalTestBtn'),
    channelModalTestFeedback: document.getElementById('channelModalTestFeedback'),
    channelModalWhatsAppSection: document.getElementById('channelModalWhatsAppSection'),
    channelModalCustomSection: document.getElementById('channelModalCustomSection'),
    incomingWebhookSnippetTabs: document.getElementById('incomingWebhookSnippetTabs'),
    incomingWebhookSnippetCode: document.getElementById('incomingWebhookSnippetCode'),
    incomingWebhookUrlDisplay: document.getElementById('incomingWebhookUrlDisplay'),
    copyIncomingWebhookUrlBtn: document.getElementById('copyIncomingWebhookUrlBtn'),
};
